### ISSUE TITLE
关于您的DA-MIDL程序的一些问题

### ISSUE THREAD

**Issue by Ethanzhou09** [zhuwenyong97/DA-MIDL#2]
您好，
我在复现您的DA-MIDL程序的过程中发现train.py训练脚本若要开始训练，需要template_center_fold{}_size{}_num{}.mat文件
程序中好像并没有生成该文件的程序
我阅读了您关于此程序的论文，好像是要使用T检验的方法将MR图像分成Patch，
您能否分享一下从MR图像生成template_center_fold{}_size{}_num{}.mat的程序，
以及您使用的template_center_fold{}_size{}_num{}.mat文件呢

**Comment by xia-jingyu** [comment]
同上，希望您可以分享一下，万分感激~

**Comment by WyZhuNUAA** [comment]
您的邮件我已经收到了。Thank you.Zhu Wenyong

**Comment by Z1Ting** [comment]
同上 希望您可以分享一下，十万分感激~

**Comment by kanggege666** [comment]
求分享！十分感谢！ 我已发您邮箱！

**Comment by WyZhuNUAA** [comment]
您的邮件我已经收到了。Thank you.Zhu Wenyong

**Comment by Z1Ting** [comment]
寄&nbsp; &nbsp;邮箱没收到啊



------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年6月15日(星期三) 中午11:35
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [WyZhuNUAA/DA-MIDL] 关于您的DA-MIDL程序的一些问题 (Issue #2)





您的邮件我已经收到了。谢谢朱文勇
—
直接回复此邮件，在 GitHub 上查看或取消订阅.
你收到这个是因为你评论了。留言 ID ***@***.***与&gt;

**Comment by WyZhuNUAA** [comment]
您的邮件我已经收到了。Thank you.Zhu Wenyong
